#!name=Sub-Store
#!desc=Sub-Store

[Script]

sub-store-1.min_1 = type=http-request, pattern=^https?:\/\/sub\.store\/((download)|api\/(preview|sync|(utils\/node-info))), requires-body=true, max-size=3145728, script-path=https://github.com/sub-store-org/Sub-Store/releases/latest/download/sub-store-1.min.js, timeout=60, script-update-interval=0

sub-store-0.min_2 = type=http-request, pattern=^https?:\/\/sub\.store, requires-body=true, max-size=3145728, script-path=https://github.com/sub-store-org/Sub-Store/releases/latest/download/sub-store-0.min.js, timeout=60, script-update-interval=0

[MITM]

hostname = %APPEND% sub.store
